sudo: required
services:
  - docker

language: java
jdk:
  - oraclejdk8

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - cd lareleve
  - gradle buildImage --stacktrace

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then; docker push gattazr/lareleve:latest; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then; docker push gattazr/lareleve:latest; fi

cache:
  directories:
    - "$HOME/.gradle"

branches:
  only:
    - master
    - develop
